const Lang = {
  en: {
    search: "Search",
    Placeholder: "What would you like to see today?",
    SignIn: "Sign In",
    SignUp: "Sign Up",
    existingUser: "Existing User?",
    signInNow: "Sign in now",
    loginEmailPlaceholder: "Email or phone number",
    loginPasswordPlaceholder: "Password",
    loginNamePlaceholder: "Name",
    RememberME: "Remember me",
    needHelp: "Need help?",
    newToNetflix: "New to Netflix?",
    signUpNow: "Sign up now",
    protected:
      "This page is protected by Google reCAPTCHA to ensure you're not a bot.",
    learnMore: "Learn more.",
  },
  hindi: {
    search: "खोज",
    Placeholder: "आज आप क्या देखना चाहेंगे? ",
    SignIn: "साइन इन करें",
    SignUp: "साइन अप करें",
    existingUser: "मौजूदा उपयोगकर्ता?",
    signInNow: "साइन इन करो",
    loginEmailPlaceholder: "ईमेल या फ़ोन नंबर",
    loginPasswordPlaceholder: "पासवर्ड",
    loginNamePlaceholder: "नाम",
    RememberME: "मुझे याद रखना",
    needHelp: "मदद की ज़रूरत है?",
    newToNetflix: "नेटफ्लिक्स पर नए हैं?",
    signUpNow: "साइनअप करें",
    protected:
      "यह पृष्ठ Google reCAPTCHA द्वारा सुरक्षित है ताकि यह सुनिश्चित किया जा सके कि आप बॉट नहीं हैं।",
    learnMore: "और अधिक जानें।",
  },
  spanish: {
    search: "Buscar",
    Placeholder: "¿Qué te gustaría ver hoy?",
    SignIn: "Iniciar sesión",
    SignUp: "Inscribirse",
    existingUser: "¿Usuario existente?",
    signInNow: "Regístrate",
    loginEmailPlaceholder: "Correo electrónico o número de teléfono",
    loginPasswordPlaceholder: "Contraseña",
    loginNamePlaceholder: "Nombre",
    RememberME: "Acuérdate de mí",
    needHelp: "¿Necesitas ayuda?",
    newToNetflix: "¿Nuevo en Netflix?",
    signUpNow: "Regístrate ahora",
    protected:
      "Esta página está protegida por Google reCAPTCHA para garantizar que no seas un bot.",
    learnMore: "Aprende más.",
  },
};
export default Lang;
